server:
  port: 8081

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/snopy_dev?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml
  type-aliases-package: com.latagui.dao

#showSql
logging:
  level:
    com:
      example:
        mapper : debug
